sonar.projectKey=devxxmx_saas
sonar.organization=devxxmx
sonar.projectName=School SaaS Management
sonar.python.version=3.11
sonar.sources=school_saas,school-saas-frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**,**/build/**,**/__pycache__/**
