# Generated by Django 6.0.4 on 2026-04-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
    ]
