# Generated by Django 6.0.4 on 2026-04-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
    ]
